name: My Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check User
      run: |
        allowed_users = "nishithdev"
        current_user = ${{ github.actor }}
        if current_user in allowed_users:
          echo "User is allowed"
        else:
          echo "User is not allowed"
