name: My Workflow

on: [push]

env:
  ALLOWED_USERS: "nishithdev,b,c,d,e"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check User
      run: |
        allowed_users = [user.strip() for user in os.environ['ALLOWED_USERS'].split(',')]
        current_user = ${{ github.actor }}
        if current_user in allowed_users:
          echo "User is allowed"
        else:
          echo "User is not allowed"
